import mongoose from 'mongoose'

/**
 * DoubtSignal — Contextual Doubt-Anchored Polling
 *
 * Captures the exact moment a student loses the thread. Stored anonymously:
 * the `studentHash` is HMAC-SHA256(userId, roomSalt) — a teacher cannot reverse
 * it back to a user, but the same student is counted once per question if they
 * mark again later (aggregation treats them as one).
 *
 * Per-room `salt` lives on Room.doubtSalt; generated by the doubtService when
 * the first signal arrives, regenerated when the room ends (so signatures
 * don't carry over across sessions).
 */
const doubtSignalSchema = new mongoose.Schema({
  roomId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Room',
    required: true
  },
  studentHash: {
    type: String,
    required: true,
    match: /^[a-f0-9]{64}$/,
    index: true
  },
  segmentIndex: {
    type: Number,
    required: true,
    min: 0,
    index: true
  },
  // milliseconds offset within the segment where the student clicked
  transcriptOffsetMs: {
    type: Number,
    default: 0,
    min: 0
  },
  // Whether the student later retracted this signal within the retract window
  retracted: {
    type: Boolean,
    default: false
  },
  // Client-supplied context (optional): device type, etc. — kept generic to
  // avoid leaking identity info.
  client: {
    type: { type: String, default: 'unknown' }
  },
  createdAt: {
    type: Date,
    default: Date.now,
    index: true
  }
})

// Composite index: room + segment gives fast aggregation per-segment counts.
// Created with TTL removed; data is intentionally retained for analysis.
doubtSignalSchema.index({ roomId: 1, segmentIndex: 1 })
// One student can only have a single active signal per segment (duplicate taps are
// ignored at write time, not via a unique index so we can keep multiple historical
// signals if retraction toggling is enabled).

// Used by doubtful aggregation: count distinct students per segment.
doubtSignalSchema.statics.countDistinctStudentsBySegment = async function (roomId) {
  return this.aggregate([
    { $match: { roomId: new mongoose.Types.ObjectId(String(roomId)), retracted: false } },
    { $group: { _id: '$segmentIndex', uniqueStudents: { $addToSet: '$studentHash' } } },
    { $project: { segmentIndex: '$_id', count: { $size: '$uniqueStudents' }, _id: 0 } },
    { $sort: { segmentIndex: 1 } }
  ])
}

const DoubtSignal = mongoose.model('DoubtSignal', doubtSignalSchema)
export default DoubtSignal